### ISSUE TITLE
Consider mutter instead of Xvfb

### ISSUE THREAD

**Issue by mickaelistria** [pyvista/setup-headless-display-action#6]
I'm currently using the xvfb-action in some workflows. I'd like to get rid of Xvfb and to use headless mutter instead, which is available since Gnome 40: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1698
Would it make sense for this action?

**Comment by banesullivan** [comment]
I'm not well versed in the differences/motivation but I'm open to reviewing a PR with the change.

My main concern is that there are a lot of downstream repos using this action and are using `xvfb-run` in their workflows.

----

Honestly, I'm hoping we (being PyVista projects) can move away from this whole action now that we are building VTK wheels with different graphics backends; eliminating the need for a virtual frame buffer altogether.

This is further motivated by how we've been unable to update OSMesa on Windows.

**Comment by mickaelistria** [comment]
OK, it looks like this is not really in the scope of this project. I'm going to close it.
In the meantime, I found this simple build step allows to replace Xvfb by mutter in my workflows, without having to adapt other steps

```yaml
- name: Setup Display 📺
  run: |
     sudo apt-get install mutter dbus-x11;
     dbus-launch --auto-syntax > dbus-env;
     . dbus-env;
     mutter --no-x11 --headless --virtual-monitor 1920x1080 &
```
